_target_: lightning.fabric.Fabric
devices: 1
num_nodes: 1
strategy: "auto"
accelerator: "cpu"
precision: "32-true"
callbacks:
  - _target_: utils.callback.CheckpointCallback
    keep_last: "${checkpoint.keep_last}"
