defaults:
  - default
  - _self_

# Override from `default` config
id: interoceptiveAI
action_repeat: 1
capture_video: False
reward_as_observation: False
port: 3001
config: train-level-1
screenRecordEnable: False
dataRecordEnable: False
recordingFolder: Recordings
baseFolderName: Data
fileNamePrefix: data
base_dir: "./envs"
time_scale: 15
width: 100
height: 100

# Wrapper to be instantiated
wrapper:
  _target_: envs.interoceptiveAI.InteroceptiveAIWrapper
  id: ${env.id}
  screen_size: ${env.screen_size}
  seed: ${seed}
  env_cfg:
    env:
      base_dir_: ${env.base_dir}
      env_name: evaaa 
      config_: ${env.config}
      env_port: ${env.port}
      use_reward_shaping: true
      # num_envs: 1
      screenRecordEnable_: ${env.screenRecordEnable}
      dataRecordEnable_: ${env.dataRecordEnable}
      recordingFolder_: ${env.recordingFolder}
      baseFolderName_: ${env.baseFolderName}
      fileNamePrefix_: ${env.fileNamePrefix}

    engine_configuration:  # for stimulating Unity 
      time_scale: ${env.time_scale} # speeding
      width: ${env.width}
      height: ${env.height}
      no_graphics: false

    environment_parameters:   
      common:
        singleTrial: false    # Checking for success in specific experiments (Not available now)
      ev:   # for defining EV parameters
        evSize: 4
      # for sensor parameters
      visualSensor:
        useVisual: true
        visualHight: 64
        visualWidth: 64

      olfactorySensor:
        useOlfactory: true
        olfactorySensorLength: 100
        olfactoryFeatureSize: 10

      thermoSensor:
        useThermo: true
        thermoSensorChangeRate: 10
        thermoSensorSize: 8

      collisionSensor:
        useCollision: true
        collisionSensorSize: 10

      touchSensor:
        useTouchObs: true
        touchSensorSize: 1
